# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: pygments
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: DMPED Great Streets Dashboard
subtitle: 'Deputy Mayor for Planning & Economic Development | Muriel Bowser, Mayor'

# Author/Organization info to be displayed in the templates
author:
  name: Office of the Deputy Mayor for Planning and Economic Development
  url: http://dmped.dc.gov

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/great-streets'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: '/assets/img/we-are-wdc.png'
logoalt: We Are Washington DC

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: 'Great Streets Map'
  internal: true
  url: ./
- text: '7th St NW/ Georgia Ave NW'
  internal: true
  url: 7th-georgia.html
- text: 'Connecticut Ave NW'
  internal: true
  url: employment-labor.html
- text: 'Georgia Ave NW'
  internal: true
  url: income-wages-taxes.html
- text: 'H St NE - Bladensburg Rd NE'
  internal: true
  url: housing-indicators.html
- text: 'Minnesota Ave NE - Benning Rd NE'
  internal: true
  url: construction-activity.html
- text: 'Martin Luther King Jr Ave'
  internal: true
  url: affordable-production-preservation.html
- text: 'Nannie Helen Burroughs Ave'
  internal: true
  url: dmped-real-estate.html
- text: 'New York Ave'
  internal: true
  url: chart-of-the-week.html
- text: 'North Capitol St'
  internal: true
  url: chart-of-the-week.html  
- text: 'Pennsylvania Ave'
  internal: true
  url: chart-of-the-week.html
- text: 'Rhode Island Ave'
  internal: true
  url: chart-of-the-week.html
- text: 'U St - 14th St'
  internal: true
  url: chart-of-the-week.html
- text: 'Wisconsin Ave NW'
  internal: true
  url: chart-of-the-week.html
# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: great-streets
  description:
  url: https://github.com/DCgov/great-streets

google_analytics_ua: UA-2638726-1

# Style Variables
brand_color: "#BF0000"
